{% set name = "fftlog" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 049d420c6dbbc85b79a7682764228092cd395210b37c9c9ae909e645822210d2

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv  # [unix]
    - {{ PYTHON }} -m pip install . -vv --global-option=build_ext --global-option --compiler=mingw32  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - pip
    - numpy
    - python
    - m2w64-gcc-libgfortran   # [win]
  run:
    - python
    - scipy
    - libgfortran-ng          # [not win]
    - libgfortran             # [osx]
    - {{ pin_compatible('m2w64-gcc-libgfortran', max_pin='x') }}   # [win]

test:
  imports:
    - fftlog

about:
  home: https://github.com/prisae/fftlog
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: 'Logarithmic Fast Fourier Transform'
  description: |
    A simple python-wrapper for the logarithmic FFT code FFTLog
    as presented in Appendix B of Hamilton (2000) and published at
    casa.colorado.edu/~ajsh/FFTLog.
  doc_url: https://pyfftlog.readthedocs.io/
  dev_url: https://github.com/prisae/fftlog

extra:
  recipe-maintainers:
    - prisae
